# Pandas

pandas专门处理表格和混杂数据，NumPy更适合处理统一的数值数组数据

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

# Pandas数据结构介绍

## Series

Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
# Series的字符串表现形式为：索引在左边，值在右边
# 由于没有为数据指定索引，所以会自动创建一个0到N-1的数据型索引（N为数据长度）
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
# 通过Series的value和index属性获取其数组表示形式和索引对象
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index  # 类似range(4)

RangeIndex(start=0, stop=4, step=1)

In [7]:
# 通常我们所创建的Series带有一个可以对各个数据点进行标记的索引
obj2 = pd.Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
# 可以通过索引的方式选取Series中的单个或一组值
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
# ['c', 'a', 'd']是索引列表，即使它包含的是字符串而不是整数
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
# 使用NumPy函数或类似NumPy的运算都会保留索引值的链接
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
# 将Series看成一个定长的有序字典，因为它是索引值到数据值的一个映射
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
# 如果数据被存放在一个Python字典中，也可以直接通过这个字典创建Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
# 如果只传入一个字典，则结束Series中的索引就是原字典的键（有序排列）
# 可以传入排好序的字典的键以改变顺序
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = pd.Series(sdata, index = states)

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
# 在pandas中，NaN（非数字）用于表示缺失或Na值
# isnull和notnull函数可以用于检测缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
# Series也有类似的实例方法
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
# Series会根据运算的索引标签自动对齐数据，类似join的操作
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
# Series对象本身及其索引都有一个name属性
obj4.name = 'population'

In [32]:
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
# Series的索引可以通过赋值的方式就地修改
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）

DataFrame既有行索引也有列索引，可以被看做由Series组成的字典（共用同一个索引）

DataFrame中的数据是以一个或多个二维块存放的。

In [38]:
# 直接传入一个由等长列表或NumPy数组组成的字典
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year':[2000, 2001, 2002, 2001, 2002, 2003],
        'pop':[1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [39]:
# 结果DataFrame会自动加上索引，且全部会被有序排列
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [40]:
# 对特别大的DataFrame，head方法会选取前五行
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [41]:
# 如果指定了序列，DataFrame的列会按照指定顺序进行排列
pd.DataFrame(data, columns = ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [43]:
# 如果传入的列在数据中找不到，就会在结果中产生缺失值
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
                      index = ['one', 'two', 'three', 'four', 'five', 'six'])

In [44]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [45]:
# 通过类似字典标记的方法或属性的方式，可以将DataFrame的列获取为一个Series
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [47]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

注意：返回的Series拥有原DataFrame相同的所有，且其name属性也已经被相应设置好了

In [48]:
# 行也可以通过位置或名称的方式进行获取
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [49]:
# 列可以通过赋值的方式修改
frame2['debt'] = 16.5

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [52]:
frame2['debt'] = np.arange(6.)

In [53]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [54]:
# 将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配
# 如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失值
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])

In [55]:
frame2['debt'] = val

In [56]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [57]:
# 为不存在的列赋值会创建出一个新列。关键字del删除列
frame2['estern'] = frame2.state == 'Ohio'

In [58]:
frame2

year   state  pop  debt  estern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False

注意：不能用frame2.eastern创建新的列

In [60]:
# del方法可以删除该列
del frame2['estern']

In [61]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

注意：通过索引方式返回的列是相应数据的视图，不是副本。对返回的Series做的修改都会反映到源DataFrame上。通过Series的copy方法可指定复制列

In [62]:
pop = {'Nevada':{2001: 2.4, 2002: 2.9},
       'Ohio':{2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [63]:
#如果嵌套字典传给DataFrame，pandas会被解释为：外层字典的键作为列，内层键作为行索引
frame3 = pd.DataFrame(pop)

In [64]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [65]:
# 可以使用类似NumPy数组的方法，对DataFrame进行转置（交换行和列）：
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [68]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [72]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [73]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [98]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio':{2000: 1.5, 2001: 1.7, 2002: 3.6}}
pd.DataFrame(pop,columns=['Nevada', 'Ohio'], index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [88]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [91]:
frame3 = pd.DataFrame(pop)
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [92]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [93]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [94]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [96]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [99]:
# values属性也会以二维ndarray的形式返回DataFrame中的数据
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [101]:
# 如果DataFrame各列的数据类型不同，则值数组的dtype就会选用能兼容所有列的数据类型
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

pandas的索引对象负责管理轴标签和其他元数据（比如轴名称等）

In [102]:
# 构建Series或DataFrame时，所用到的任何数组或其他序列的标签都会被转换成一个Index
obj = pd.Series(range(3), index = ['a', 'b', 'c'])

In [103]:
index = obj.index

In [104]:
index

Index(['a', 'b', 'c'], dtype='object')

In [105]:
index[1:]

Index(['b', 'c'], dtype='object')

In [106]:
# Index对象是不可变的，因此用户不能对其进行修改
index[1] = 'd'  # 会出错

TypeError: Index does not support mutable operations

In [108]:
# 不可变可以使Index对象在多个数据结构之间安全共享
labels = pd.Index(np.arange(3))

In [109]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [110]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [111]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [113]:
obj2.index is labels

True

In [114]:
# Index的功能也类似一个固定大小的集合
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [115]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [116]:
'Ohio' in frame3.columns

True

In [117]:
2003 in frame3.index

False

In [118]:
# pandas的Index可以包含重复的标签
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [119]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# 基本功能

## 重新索引

In [120]:
# reindex方法的作用：创建一个新对象，它的数据符合新的索引
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])

In [121]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [122]:
# 用该Series的reindex会根据新索引进行重排
# 如果某个索引值当前不存在，就引入缺失值
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [123]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [124]:
# 对于时间序列这样的有序数据，重新索引时可能需要做插值处理
# method选项可以实现，如使用ffill实现前向值填充
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])

In [125]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [126]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [127]:
# 借助DataFrame，reindex可以修改（行）索引和列
# 只传递一个序列时，会重新索引结果的行
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index = ['a', 'c', 'd'],
                    columns = ['Ohio', 'Texas', 'California'])

In [128]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [129]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [130]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [131]:
# 列可以用columns关键字重新索引
states = ['Texas', 'Utah', 'California']

In [132]:
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 丢弃指定轴上的项

In [135]:
# 只要有一个索引数组或列表即可丢弃某条轴上的一个或多个项
# drop方法返回一个在指定轴上删除了指定值的新对象
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])

In [136]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [137]:
new_obj = obj.drop('c')

In [138]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [141]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [143]:
# drop返回的是一个新对象，原来的obj没变
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [144]:
# 对于DataFrame，可以删除任意轴上的索引值
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])

In [145]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
# 用标签序列调用drop从行标签(axis 0)删除值
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [147]:
# 通过传递axix = 1或axis = 'columns'可以删除列的值
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [148]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [150]:
# 可直接修改对象，而不是返回新对象。设置inplace属性为True
obj.drop('c', inplace = True)

In [151]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## 索引，选取和过滤

In [153]:
# Series索引(obj[...])的工作方式类似于NumPy数组的索引
# Series索引的值不只是整数
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])

In [154]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [155]:
obj['b']

1.0

In [156]:
obj[1]

1.0

In [157]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [158]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [159]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [160]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [161]:
# 利用标签的切片运算与普通的Python切片运算不同，它包含末端
obj['b': 'c']

b    1.0
c    2.0
dtype: float64

In [162]:
# 用切片可以对Series的相应部分进行设置
obj['b', 'c'] = 5

In [163]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [164]:
# 用一个值或序列对DataFrame进行索引其实就是获取一个或多个列
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])

In [165]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [166]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [167]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [168]:
# 通过切片或布尔型数组选取数据
# 用data[:2]选取行
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [169]:
# 向[]传递单一的元素或列表，就可选择列
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [170]:
# 通过布尔型DataFrame进行索引
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [171]:
data[data < 5] = 0

In [172]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 用loc和iloc进行选取

In [173]:
# 使用轴标签（loc）或整数索引（iloc），从DataFrame选择行和列的子集
# 通过标签选取一行和多列
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [174]:
# 用iloc和整数进行选取
# 第二行的第3,0,1列
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [175]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [176]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [177]:
# 这两个索引函数也适用于一个标签或多个标签的切片
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [178]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

## 整数索引

In [179]:
ser = pd.Series(np.arange(3.))

In [180]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [181]:
# 整数索引会出错
ser[-1]

KeyError: -1

In [183]:
ser2 = pd.Series(np.arange(3.), index = ['a', 'b', 'c'])

In [185]:
# 非整数索引不会
ser2[-1]

2.0

In [186]:
# 因此如果轴索引含有整数，数据选取则需要使用标签
# 即loc（标签）或iloc（整数）
ser[:1]

0    0.0
dtype: float64

In [187]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [188]:
ser.iloc[:1]

0    0.0
dtype: float64

## 算数运算和数据对齐

pandas最重要的一个功能是它可以对不同索引的对象进行算术运算

将对象相加时，如果存在不同的索引，则结果的索引就是该索引对的并集

类似在索引标签上进行自动外连接

In [189]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])

In [190]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index = ['a', 'c', 'e', 'f', 'g'])

In [191]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [192]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [193]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [195]:
# 对于DataFrame，对齐操作会同时发生在行和列上
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                  columns = list('bcd'),
                  index = ['Ohio', 'Texas', 'Colorado'])

In [196]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                  columns = list('bde'),
                  index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [197]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [198]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [199]:
# 它们相加后会返回一个新的DataFrame，其索引和列为原来那两个DataFrame的并集
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

因为c和e列没有同时存在于两个DataFrame对象中，在结果中以缺省值呈现。行类似

In [200]:
# 如果DataFrame对象相加，没有共用的列或行标签，结果都会是空
df1 = pd.DataFrame({'A': [1, 2]})

In [201]:
df2 = pd.DataFrame({'B': [3, 4]})

In [202]:
df1

A
0  1
1  2

In [203]:
df2

B
0  3
1  4

In [204]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### 在算术方法中填充值

In [205]:
# 有时希望当一个对象中某个轴标签在另一个对象中找不到时填充一个特殊值（如0）
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns = list('abcd'))

In [208]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns = list('abcde'))

In [209]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [210]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [211]:
df2.loc[1, 'b'] = np.nan

In [212]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [213]:
# 它们相加时没有重叠的位置就会产生NA值
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [215]:
# 使用df1的add方法传入df2及一个fill_value参数
df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [216]:
# 以字母r开头的运算会翻转参数
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [217]:
df1.rdiv(1)  #与上面等价

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [218]:
# 在对Series或DataFrame重新索引时也可以指定一个填充值
df1.reindex(columns = df2.columns, fill_value = 0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### DataFrame和Series之间的运算

In [219]:
# 计算一个二维数组与其某行之间的差
arr = np.arange(12.).reshape((3, 4))

In [220]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [221]:
arr[0]

array([0., 1., 2., 3.])

In [222]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

当从arr减去arr[0]，每一行都会执行这个操作。称之为广播。DataFrame和Series之间的运算也是如此

In [223]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [224]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [225]:
series = frame.iloc[0]

In [226]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [227]:
# 默认情况下DataFrame和Series之间的算术运算会将Series的索引匹配到DataFrame的列，然后沿着行一直向下广播
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [228]:
# 如果某个索引值在DataFrame的列或Series的索引中找不到，则参与运算的两个对象就会被重新索引以形成并集
series2 = pd.Series(range(3), index = ['b', 'e', 'f'])

In [229]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [230]:
series2

b    0
e    1
f    2
dtype: int64

In [231]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [232]:
# 如果希望匹配行，且在列上广播，则必须使用算术运算方法
series3 = frame['d']

In [233]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [234]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [235]:
# 传入的轴号就是希望匹配的轴。这里的目的是匹配DataFrame的行索引并进行广播
frame.sub(series3, axis = 'index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## 函数应用和映射

In [236]:
# NumPy的ufuncs（元素级数组方法）也可用于操作pandas对象
frame = pd.DataFrame(np.random.randn(4, 3),
                    columns = list('bde'),
                    index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [238]:
frame

b         d         e
Utah    0.902585 -0.087053 -0.549459
Ohio    0.782350 -1.786948  0.617030
Texas   0.279038  1.511976  1.135883
Oregon  0.262950 -0.899144  0.396761

In [239]:
np.abs(frame)

b         d         e
Utah    0.902585  0.087053  0.549459
Ohio    0.782350  1.786948  0.617030
Texas   0.279038  1.511976  1.135883
Oregon  0.262950  0.899144  0.396761

In [240]:
# 将函数应用到由各列或行所形成的一位数组上
# DataFrame的apply方法可实现此功能
f = lambda x: x.max() - x.min()

In [241]:
frame.apply(f)

b    0.639635
d    3.298924
e    1.685342
dtype: float64

上面的函数f计算了一个Series的最大值和最小值的差，在frame的每列都执行了一次。

结果是一个Series，使用frame的列作为索引

In [242]:
# 若传递axis = 'columns'到apply方法，这个函数会在每行执行
frame.apply(f, axis = 'columns')

Utah      1.452043
Ohio      2.569298
Texas     1.232938
Oregon    1.295904
dtype: float64

In [243]:
# 传递到apply的函数不是必须返回一个标量，还可以返回由多个值组成的Series
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [244]:
frame.apply(f)

b         d         e
min  0.262950 -1.786948 -0.549459
max  0.902585  1.511976  1.135883

In [245]:
# 元素级的Python函数也可以用
# 若想得到frame中各个浮点值的格式化字符串，使用applymap即可
format = lambda x: '%.2f' % x

In [246]:
frame.applymap(format)

b      d      e
Utah    0.90  -0.09  -0.55
Ohio    0.78  -1.79   0.62
Texas   0.28   1.51   1.14
Oregon  0.26  -0.90   0.40

In [247]:
# 之所以叫applymap，是因为Series有一个用于应用元素级函数的map方法
frame['e'].map(format)

Utah      -0.55
Ohio       0.62
Texas      1.14
Oregon     0.40
Name: e, dtype: object

## 排序和排名

In [248]:
# 根据条件对数据集排序是一种重要的内置运算
# 要对行或列索引进行排序（按字典排序），可以使用sort_index方法，返回一个已排序的新对象
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])

In [249]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [250]:
# 对于DataFrame，可以根据任意一个轴上的索引进行排序
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index = ['three', 'one'],
                    columns = ['d', 'a', 'b', 'c'])

In [251]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [252]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [253]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [254]:
# 数据默认是按升序排列的，也可以按降序排列
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [255]:
# 若要按值对Series进行排序，可使用sort_values方法
obj = pd.Series([4, 7, -3, 2])

In [256]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [257]:
# 排序时，任何缺失值默认都会被放到Series的末尾
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [258]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [259]:
# 当排序一个DataFrame时，可能希望根据一个或多个列中的值进行排序
# 将一个或多个列的名字传递给sort_values的by选项即可达到该目的
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [260]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [261]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [262]:
# 要根据多个列进行排序，传入名称的列表即可
frame.sort_values(by = ['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [263]:
# 排名会从1开始一直到数组中有效数据的数量
# rank方法是通过“为各组分配一个平均排名”的方式破坏平衡关系的
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [264]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

对上述结果的解释：rank 表示这个数在原来的向量中排第几名，有相同的数，按最小排序，取平均（默认）。

第一行的 0 指第一个数，即7，应该排名第 7 ，但是第 6 和 第 7 都是 7，因此取平均值6.5

第二行的 1 指第二个数，即-5，应该排名第 1，所以是 1

In [265]:
# 也可以根据值在原数据中出现的顺序给出排名
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

这里第一行和第三行，即第0个数和第2个数没有用平均排名6.5，被设置成了6和7，因为数据中标签0位于标签2前面

In [266]:
# 也可以按降序进行排名
# method = 'max'表示显示最大的排名
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [267]:
# DataFrame可以在行或列上计算排名
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],'c': [-2, 5, 8, -2.5]})

In [268]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [269]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 带有重复标签的轴索引

In [270]:
obj = pd.Series(range(5), index = ['a', 'a', 'b', 'b', 'c'])

In [271]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [272]:
# 索引的is_unique属性告诉你它的值是否唯一
obj.index.is_unique

False

In [273]:
# 如果某个索引对应多个值，则返回一个Series
# 如果对应单个值，则返回一个标量值
obj['a']

a    0
a    1
dtype: int64

In [274]:
obj['c']

4

In [275]:
# 对DataFrame的行进行索引
df = pd.DataFrame(np.random.randn(4, 3), index = ['a', 'a', 'b', 'b'])

In [276]:
df

0         1         2
a -0.547288 -0.513102 -1.512890
a  0.362943  0.276936 -0.914875
b -1.435167 -0.881613  1.008472
b  0.572725  0.941784 -0.849325

In [277]:
df.loc['b']

0         1         2
b -1.435167 -0.881613  1.008472
b  0.572725  0.941784 -0.849325

# 汇总和计算描述统计

In [279]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
                 index = ['a', 'b', 'c', 'd'],
                 columns = ['one', 'two'])

In [280]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [282]:
# 调用DataFrame的sum方法将会返回一个含有列的和的Series
df.sum()

one    9.25
two   -5.80
dtype: float64

In [283]:
# 传入axis = 'columns'或axis = 1会按行进行求和运算
df.sum(axis = 1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [284]:
# NA值会自动被排除，除非整个行或列都是NA
# 通过skipna选项可以禁用该功能
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [285]:
# 有些方法返回的是间接统计
# 比如达到最小值或最大值的索引
df.idxmax()

one    b
two    d
dtype: object

In [286]:
# 累计型方法
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [287]:
# describe用于一次性产生多个汇总统计
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [288]:
# 对于非数值型数据，describe会产生另外一种汇总统计
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [289]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## 相关系数与协方差

Series的corr方法用于计算两个Series中重叠的、非NA的、按索引对其的值的相关系数。

与此类似，cov用于计算协方差

## 唯一值、值计数以及成员资格

In [6]:
# 从一维Series的值中抽取信息
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [7]:
# unique函数可以得到Series中的唯一值数组
uniques = obj.unique()

In [8]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [9]:
# 返回的唯一值是未排序的，如果需要的话可以对结果再次进行排序（uniques.sort()）
# value_counts用于计算一个Series中各值出现的频率
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [10]:
# 结果是按照值频率降序排列的
# value_counts可用于任何数组或序列
pd.value_counts(obj.values, sort = False)

c    3
b    2
a    3
d    1
dtype: int64

In [11]:
# isin用于判断矢量化集合的成员资格，可用于过滤Series中或DataFrame列中数据的子集
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [12]:
mask = obj.isin(['b', 'c'])

In [13]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [14]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [15]:
# Index.get_indexer方法可以给你一个索引数组，从可能包含重复值的数组到另一个不同值的数组
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [16]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [17]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [18]:
unique_vals

0    c
1    b
2    a
dtype: object

In [19]:
# 表示 to_match 中的字符，在 unique_vals 中的位置索引
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [20]:
# 得到DataFrame中多个相关列的一张柱状图
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 5, 2, 4, 4]})

In [21]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [22]:
# 将panda.value_counts传给该DataFrame的apply函数
result = data.apply(pd.value_counts).fillna(0)

In [23]:
# 结果中的行标签是所有列的唯一值，后面的频率是每个列中这些值的相应计数
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

# 读写文本格式的数据

In [26]:
df = pd.read_csv('ex1.csv')

In [27]:
df

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [29]:
# 可以用read_table，并指定分隔符
pd.read_table('ex1.csv', sep = ',')

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo